import = ["~/.config/alacritty/theme"]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/fish"

[window]
opacity = 1
padding = { x = 30, y = 40 }
# startup_mode = "Maximized"
decorations = "Full"
blur = true

[font]
normal = { family = "JetBrains Mono", style = "regular" }
size = 11

[cursor]
blink_interval = 600
blink_timeout = 0
style = { shape = "Block", blinking = "Always" }

